[package]
name = "steganography_service"
version = "0.1.0"
edition = "2024"

[dependencies]
shared_global = { path = "../shared/global" }
axum = "0.7"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
dotenvy = "0.15"
