services:

  steganography_service:
    build:
      context: ..
      dockerfile: steganography_service/Dockerfile
    container_name: steganography_service
    environment:
      JWT_SECRET: ${JWT_SECRET:-my-super-duper-mega-secret-key-that-no-one-will-discover-btw-have-you-played-silksong-yet-its-so-fucking-amazing-dude-i-cant-even-start-to-explain-how-much-i-love-it}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY:-zero-trust-they-said-itll-be-fun-they-said-now-im-just-a-microservice-with-trust-issues-talking-to-myself-through-http-requests}
      RUST_LOG: info
      PORT: 3003
    ports:
      - "3003:3003"
    # depends_on:
    # networks:

# volumes:

networks:
  auth_network:
    driver: bridge
    name: microservices_network
    external: true
